// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkH7w6iAb15svQvXrDUtzc5u0y7tMK8g',
    appId: '1:935585769756:web:7551eb0ae641d727b832d9',
    messagingSenderId: '935585769756',
    projectId: 'flutter-app-b9d57',
    authDomain: 'flutter-app-b9d57.firebaseapp.com',
    storageBucket: 'flutter-app-b9d57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZzyRGe89l-DfgzTJjSjxeNmM1gx2OJU',
    appId: '1:935585769756:android:694475b7c861d44ab832d9',
    messagingSenderId: '935585769756',
    projectId: 'flutter-app-b9d57',
    storageBucket: 'flutter-app-b9d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXoJ1h2V3hotKVvK5dOmmgU0hPKVlQEc',
    appId: '1:935585769756:ios:e4b79d80e13365a4b832d9',
    messagingSenderId: '935585769756',
    projectId: 'flutter-app-b9d57',
    storageBucket: 'flutter-app-b9d57.appspot.com',
    iosBundleId: 'dk.kennik.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXoJ1h2V3hotKVvK5dOmmgU0hPKVlQEc',
    appId: '1:935585769756:ios:225721e1d2be6dd7b832d9',
    messagingSenderId: '935585769756',
    projectId: 'flutter-app-b9d57',
    storageBucket: 'flutter-app-b9d57.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
